INSERT INTO course (name, credits, branch, semester) VALUES ('Cloud Computing - Sem 1 (CSE)', 4, 'CSE', 1);
INSERT INTO course (name, credits, branch, semester) VALUES ('Data Structures - Sem 1 (CSE)', 5, 'CSE', 1);
INSERT INTO course (name, credits, branch, semester) VALUES ('Machine Learning - Sem 1 (CSE)', 4, 'CSE', 1);
INSERT INTO course (name, credits, branch, semester) VALUES ('Web Technologies - Sem 1 (CSE)', 4, 'CSE', 1);
INSERT INTO course (name, credits, branch, semester) VALUES ('Computer Networks - Sem 1 (CSE)', 5, 'CSE', 1);
INSERT INTO course (name, credits, branch, semester) VALUES ('Software Engineering - Sem 2 (CSE)', 4, 'CSE', 2);
INSERT INTO course (name, credits, branch, semester) VALUES ('Data Structures - Sem 2 (CSE)', 4, 'CSE', 2);
INSERT INTO course (name, credits, branch, semester) VALUES ('DBMS - Sem 2 (CSE)', 4, 'CSE', 2);
INSERT INTO course (name, credits, branch, semester) VALUES ('Cloud Computing - Sem 2 (CSE)', 4, 'CSE', 2);
INSERT INTO course (name, credits, branch, semester) VALUES ('Operating Systems - Sem 2 (CSE)', 5, 'CSE', 2);
INSERT INTO course (name, credits, branch, semester) VALUES ('Cloud Computing - Sem 3 (CSE)', 4, 'CSE', 3);
INSERT INTO course (name, credits, branch, semester) VALUES ('Software Engineering - Sem 3 (CSE)', 5, 'CSE', 3);
INSERT INTO course (name, credits, branch, semester) VALUES ('Operating Systems - Sem 3 (CSE)', 5, 'CSE', 3);
INSERT INTO course (name, credits, branch, semester) VALUES ('Web Technologies - Sem 3 (CSE)', 4, 'CSE', 3);
INSERT INTO course (name, credits, branch, semester) VALUES ('Artificial Intelligence - Sem 3 (CSE)', 5, 'CSE', 3);
INSERT INTO course (name, credits, branch, semester) VALUES ('Cloud Computing - Sem 4 (CSE)', 4, 'CSE', 4);
INSERT INTO course (name, credits, branch, semester) VALUES ('Web Technologies - Sem 4 (CSE)', 5, 'CSE', 4);
INSERT INTO course (name, credits, branch, semester) VALUES ('Software Engineering - Sem 4 (CSE)', 5, 'CSE', 4);
INSERT INTO course (name, credits, branch, semester) VALUES ('Operating Systems - Sem 4 (CSE)', 5, 'CSE', 4);
INSERT INTO course (name, credits, branch, semester) VALUES ('Artificial Intelligence - Sem 4 (CSE)', 5, 'CSE', 4);
INSERT INTO course (name, credits, branch, semester) VALUES ('Web Technologies - Sem 5 (CSE)', 5, 'CSE', 5);
INSERT INTO course (name, credits, branch, semester) VALUES ('DBMS - Sem 5 (CSE)', 4, 'CSE', 5);
INSERT INTO course (name, credits, branch, semester) VALUES ('Operating Systems - Sem 5 (CSE)', 5, 'CSE', 5);
INSERT INTO course (name, credits, branch, semester) VALUES ('Machine Learning - Sem 5 (CSE)', 5, 'CSE', 5);
INSERT INTO course (name, credits, branch, semester) VALUES ('Cloud Computing - Sem 5 (CSE)', 4, 'CSE', 5);
INSERT INTO course (name, credits, branch, semester) VALUES ('Algorithms - Sem 6 (CSE)', 5, 'CSE', 6);
INSERT INTO course (name, credits, branch, semester) VALUES ('Software Engineering - Sem 6 (CSE)', 4, 'CSE', 6);
INSERT INTO course (name, credits, branch, semester) VALUES ('Computer Networks - Sem 6 (CSE)', 5, 'CSE', 6);
INSERT INTO course (name, credits, branch, semester) VALUES ('Artificial Intelligence - Sem 6 (CSE)', 5, 'CSE', 6);
INSERT INTO course (name, credits, branch, semester) VALUES ('Operating Systems - Sem 6 (CSE)', 5, 'CSE', 6);
INSERT INTO course (name, credits, branch, semester) VALUES ('Operating Systems - Sem 7 (CSE)', 5, 'CSE', 7);
INSERT INTO course (name, credits, branch, semester) VALUES ('Web Technologies - Sem 7 (CSE)', 4, 'CSE', 7);
INSERT INTO course (name, credits, branch, semester) VALUES ('DBMS - Sem 7 (CSE)', 4, 'CSE', 7);
INSERT INTO course (name, credits, branch, semester) VALUES ('Computer Networks - Sem 7 (CSE)', 5, 'CSE', 7);
INSERT INTO course (name, credits, branch, semester) VALUES ('Artificial Intelligence - Sem 7 (CSE)', 5, 'CSE', 7);
INSERT INTO course (name, credits, branch, semester) VALUES ('Algorithms - Sem 8 (CSE)', 4, 'CSE', 8);
INSERT INTO course (name, credits, branch, semester) VALUES ('Software Engineering - Sem 8 (CSE)', 4, 'CSE', 8);
INSERT INTO course (name, credits, branch, semester) VALUES ('Computer Networks - Sem 8 (CSE)', 5, 'CSE', 8);
INSERT INTO course (name, credits, branch, semester) VALUES ('Cloud Computing - Sem 8 (CSE)', 4, 'CSE', 8);
INSERT INTO course (name, credits, branch, semester) VALUES ('Machine Learning - Sem 8 (CSE)', 5, 'CSE', 8);
INSERT INTO course (name, credits, branch, semester) VALUES ('Electrical Measurements - Sem 1 (EE)', 4, 'EE', 1);
INSERT INTO course (name, credits, branch, semester) VALUES ('Control Systems - Sem 1 (EE)', 4, 'EE', 1);
INSERT INTO course (name, credits, branch, semester) VALUES ('Power Electronics - Sem 1 (EE)', 5, 'EE', 1);
INSERT INTO course (name, credits, branch, semester) VALUES ('Circuit Theory - Sem 1 (EE)', 5, 'EE', 1);
INSERT INTO course (name, credits, branch, semester) VALUES ('Electrical Machines - Sem 1 (EE)', 5, 'EE', 1);
INSERT INTO course (name, credits, branch, semester) VALUES ('Renewable Energy Systems - Sem 2 (EE)', 5, 'EE', 2);
INSERT INTO course (name, credits, branch, semester) VALUES ('Electrical Measurements - Sem 2 (EE)', 4, 'EE', 2);
INSERT INTO course (name, credits, branch, semester) VALUES ('Digital Electronics - Sem 2 (EE)', 4, 'EE', 2);
INSERT INTO course (name, credits, branch, semester) VALUES ('Power Systems - Sem 2 (EE)', 4, 'EE', 2);
INSERT INTO course (name, credits, branch, semester) VALUES ('Power Electronics - Sem 2 (EE)', 5, 'EE', 2);
INSERT INTO course (name, credits, branch, semester) VALUES ('Electrical Measurements - Sem 3 (EE)', 4, 'EE', 3);
INSERT INTO course (name, credits, branch, semester) VALUES ('Power Electronics - Sem 3 (EE)', 5, 'EE', 3);
INSERT INTO course (name, credits, branch, semester) VALUES ('Digital Electronics - Sem 3 (EE)', 4, 'EE', 3);
INSERT INTO course (name, credits, branch, semester) VALUES ('Circuit Theory - Sem 3 (EE)', 5, 'EE', 3);
INSERT INTO course (name, credits, branch, semester) VALUES ('Renewable Energy Systems - Sem 3 (EE)', 5, 'EE', 3);
INSERT INTO course (name, credits, branch, semester) VALUES ('Power Systems - Sem 4 (EE)', 4, 'EE', 4);
INSERT INTO course (name, credits, branch, semester) VALUES ('Power Electronics - Sem 4 (EE)', 5, 'EE', 4);
INSERT INTO course (name, credits, branch, semester) VALUES ('Electrical Machines - Sem 4 (EE)', 4, 'EE', 4);
INSERT INTO course (name, credits, branch, semester) VALUES ('Electrical Measurements - Sem 4 (EE)', 5, 'EE', 4);
INSERT INTO course (name, credits, branch, semester) VALUES ('Renewable Energy Systems - Sem 4 (EE)', 5, 'EE', 4);
INSERT INTO course (name, credits, branch, semester) VALUES ('Renewable Energy Systems - Sem 5 (EE)', 4, 'EE', 5);
INSERT INTO course (name, credits, branch, semester) VALUES ('Signal Processing - Sem 5 (EE)', 4, 'EE', 5);
INSERT INTO course (name, credits, branch, semester) VALUES ('Control Systems - Sem 5 (EE)', 5, 'EE', 5);
INSERT INTO course (name, credits, branch, semester) VALUES ('Power Systems - Sem 5 (EE)', 5, 'EE', 5);
INSERT INTO course (name, credits, branch, semester) VALUES ('Digital Electronics - Sem 5 (EE)', 5, 'EE', 5);
INSERT INTO course (name, credits, branch, semester) VALUES ('Digital Electronics - Sem 6 (EE)', 5, 'EE', 6);
INSERT INTO course (name, credits, branch, semester) VALUES ('Signal Processing - Sem 6 (EE)', 5, 'EE', 6);
INSERT INTO course (name, credits, branch, semester) VALUES ('Control Systems - Sem 6 (EE)', 5, 'EE', 6);
INSERT INTO course (name, credits, branch, semester) VALUES ('Power Electronics - Sem 6 (EE)', 5, 'EE', 6);
INSERT INTO course (name, credits, branch, semester) VALUES ('Circuit Theory - Sem 6 (EE)', 5, 'EE', 6);
INSERT INTO course (name, credits, branch, semester) VALUES ('Electrical Measurements - Sem 7 (EE)', 4, 'EE', 7);
INSERT INTO course (name, credits, branch, semester) VALUES ('Signal Processing - Sem 7 (EE)', 4, 'EE', 7);
INSERT INTO course (name, credits, branch, semester) VALUES ('Digital Electronics - Sem 7 (EE)', 4, 'EE', 7);
INSERT INTO course (name, credits, branch, semester) VALUES ('Control Systems - Sem 7 (EE)', 4, 'EE', 7);
INSERT INTO course (name, credits, branch, semester) VALUES ('Power Electronics - Sem 7 (EE)', 4, 'EE', 7);
INSERT INTO course (name, credits, branch, semester) VALUES ('Renewable Energy Systems - Sem 8 (EE)', 5, 'EE', 8);
INSERT INTO course (name, credits, branch, semester) VALUES ('Digital Electronics - Sem 8 (EE)', 5, 'EE', 8);
INSERT INTO course (name, credits, branch, semester) VALUES ('High Voltage Engineering - Sem 8 (EE)', 4, 'EE', 8);
INSERT INTO course (name, credits, branch, semester) VALUES ('Circuit Theory - Sem 8 (EE)', 4, 'EE', 8);
INSERT INTO course (name, credits, branch, semester) VALUES ('Signal Processing - Sem 8 (EE)', 5, 'EE', 8);
INSERT INTO course (name, credits, branch, semester) VALUES ('VLSI Design - Sem 1 (ECE)', 5, 'ECE', 1);
INSERT INTO course (name, credits, branch, semester) VALUES ('Microprocessors - Sem 1 (ECE)', 5, 'ECE', 1);
INSERT INTO course (name, credits, branch, semester) VALUES ('Embedded Systems - Sem 1 (ECE)', 4, 'ECE', 1);
INSERT INTO course (name, credits, branch, semester) VALUES ('Image Processing - Sem 1 (ECE)', 5, 'ECE', 1);
INSERT INTO course (name, credits, branch, semester) VALUES ('Analog Circuits - Sem 1 (ECE)', 4, 'ECE', 1);
INSERT INTO course (name, credits, branch, semester) VALUES ('Microprocessors - Sem 2 (ECE)', 5, 'ECE', 2);
INSERT INTO course (name, credits, branch, semester) VALUES ('Signals & Systems - Sem 2 (ECE)', 5, 'ECE', 2);
INSERT INTO course (name, credits, branch, semester) VALUES ('VLSI Design - Sem 2 (ECE)', 5, 'ECE', 2);
INSERT INTO course (name, credits, branch, semester) VALUES ('Antenna Theory - Sem 2 (ECE)', 5, 'ECE', 2);
INSERT INTO course (name, credits, branch, semester) VALUES ('IoT and Applications - Sem 2 (ECE)', 4, 'ECE', 2);
INSERT INTO course (name, credits, branch, semester) VALUES ('Wireless Communication - Sem 3 (ECE)', 4, 'ECE', 3);
INSERT INTO course (name, credits, branch, semester) VALUES ('Analog Circuits - Sem 3 (ECE)', 5, 'ECE', 3);
INSERT INTO course (name, credits, branch, semester) VALUES ('Embedded Systems - Sem 3 (ECE)', 4, 'ECE', 3);
INSERT INTO course (name, credits, branch, semester) VALUES ('VLSI Design - Sem 3 (ECE)', 4, 'ECE', 3);
INSERT INTO course (name, credits, branch, semester) VALUES ('Microprocessors - Sem 3 (ECE)', 5, 'ECE', 3);
INSERT INTO course (name, credits, branch, semester) VALUES ('VLSI Design - Sem 4 (ECE)', 4, 'ECE', 4);
INSERT INTO course (name, credits, branch, semester) VALUES ('Digital Communication - Sem 4 (ECE)', 4, 'ECE', 4);
INSERT INTO course (name, credits, branch, semester) VALUES ('Microprocessors - Sem 4 (ECE)', 4, 'ECE', 4);
INSERT INTO course (name, credits, branch, semester) VALUES ('Signals & Systems - Sem 4 (ECE)', 4, 'ECE', 4);
INSERT INTO course (name, credits, branch, semester) VALUES ('Wireless Communication - Sem 4 (ECE)', 5, 'ECE', 4);
INSERT INTO course (name, credits, branch, semester) VALUES ('IoT and Applications - Sem 5 (ECE)', 4, 'ECE', 5);
INSERT INTO course (name, credits, branch, semester) VALUES ('Image Processing - Sem 5 (ECE)', 5, 'ECE', 5);
INSERT INTO course (name, credits, branch, semester) VALUES ('Microprocessors - Sem 5 (ECE)', 5, 'ECE', 5);
INSERT INTO course (name, credits, branch, semester) VALUES ('Wireless Communication - Sem 5 (ECE)', 5, 'ECE', 5);
INSERT INTO course (name, credits, branch, semester) VALUES ('VLSI Design - Sem 5 (ECE)', 5, 'ECE', 5);
INSERT INTO course (name, credits, branch, semester) VALUES ('Analog Circuits - Sem 6 (ECE)', 5, 'ECE', 6);
INSERT INTO course (name, credits, branch, semester) VALUES ('Digital Communication - Sem 6 (ECE)', 4, 'ECE', 6);
INSERT INTO course (name, credits, branch, semester) VALUES ('Embedded Systems - Sem 6 (ECE)', 5, 'ECE', 6);
INSERT INTO course (name, credits, branch, semester) VALUES ('Image Processing - Sem 6 (ECE)', 5, 'ECE', 6);
INSERT INTO course (name, credits, branch, semester) VALUES ('Wireless Communication - Sem 6 (ECE)', 5, 'ECE', 6);
INSERT INTO course (name, credits, branch, semester) VALUES ('Wireless Communication - Sem 7 (ECE)', 5, 'ECE', 7);
INSERT INTO course (name, credits, branch, semester) VALUES ('IoT and Applications - Sem 7 (ECE)', 5, 'ECE', 7);
INSERT INTO course (name, credits, branch, semester) VALUES ('Antenna Theory - Sem 7 (ECE)', 4, 'ECE', 7);
INSERT INTO course (name, credits, branch, semester) VALUES ('Microprocessors - Sem 7 (ECE)', 5, 'ECE', 7);
INSERT INTO course (name, credits, branch, semester) VALUES ('Image Processing - Sem 7 (ECE)', 5, 'ECE', 7);
INSERT INTO course (name, credits, branch, semester) VALUES ('Microprocessors - Sem 8 (ECE)', 4, 'ECE', 8);
INSERT INTO course (name, credits, branch, semester) VALUES ('Embedded Systems - Sem 8 (ECE)', 5, 'ECE', 8);
INSERT INTO course (name, credits, branch, semester) VALUES ('VLSI Design - Sem 8 (ECE)', 5, 'ECE', 8);
INSERT INTO course (name, credits, branch, semester) VALUES ('Digital Communication - Sem 8 (ECE)', 5, 'ECE', 8);
INSERT INTO course (name, credits, branch, semester) VALUES ('Analog Circuits - Sem 8 (ECE)', 4, 'ECE', 8);
INSERT INTO course (name, credits, branch, semester) VALUES ('Genetics - Sem 1 (BT)', 4, 'BT', 1);
INSERT INTO course (name, credits, branch, semester) VALUES ('Immunology - Sem 1 (BT)', 5, 'BT', 1);
INSERT INTO course (name, credits, branch, semester) VALUES ('Genetic Engineering - Sem 1 (BT)', 4, 'BT', 1);
INSERT INTO course (name, credits, branch, semester) VALUES ('Environmental Biotechnology - Sem 1 (BT)', 4, 'BT', 1);
INSERT INTO course (name, credits, branch, semester) VALUES ('Biochemistry - Sem 1 (BT)', 4, 'BT', 1);
INSERT INTO course (name, credits, branch, semester) VALUES ('Microbiology - Sem 2 (BT)', 5, 'BT', 2);
INSERT INTO course (name, credits, branch, semester) VALUES ('Cell Biology - Sem 2 (BT)', 4, 'BT', 2);
INSERT INTO course (name, credits, branch, semester) VALUES ('Biochemistry - Sem 2 (BT)', 4, 'BT', 2);
INSERT INTO course (name, credits, branch, semester) VALUES ('Plant Biotechnology - Sem 2 (BT)', 5, 'BT', 2);
INSERT INTO course (name, credits, branch, semester) VALUES ('Bioinformatics - Sem 2 (BT)', 4, 'BT', 2);
INSERT INTO course (name, credits, branch, semester) VALUES ('Environmental Biotechnology - Sem 3 (BT)', 4, 'BT', 3);
INSERT INTO course (name, credits, branch, semester) VALUES ('Immunology - Sem 3 (BT)', 5, 'BT', 3);
INSERT INTO course (name, credits, branch, semester) VALUES ('Animal Biotechnology - Sem 3 (BT)', 4, 'BT', 3);
INSERT INTO course (name, credits, branch, semester) VALUES ('Cell Biology - Sem 3 (BT)', 5, 'BT', 3);
INSERT INTO course (name, credits, branch, semester) VALUES ('Bioinformatics - Sem 3 (BT)', 4, 'BT', 3);
INSERT INTO course (name, credits, branch, semester) VALUES ('Genetic Engineering - Sem 4 (BT)', 4, 'BT', 4);
INSERT INTO course (name, credits, branch, semester) VALUES ('Bioinformatics - Sem 4 (BT)', 5, 'BT', 4);
INSERT INTO course (name, credits, branch, semester) VALUES ('Microbiology - Sem 4 (BT)', 5, 'BT', 4);
INSERT INTO course (name, credits, branch, semester) VALUES ('Immunology - Sem 4 (BT)', 5, 'BT', 4);
INSERT INTO course (name, credits, branch, semester) VALUES ('Genetics - Sem 4 (BT)', 5, 'BT', 4);
INSERT INTO course (name, credits, branch, semester) VALUES ('Genetic Engineering - Sem 5 (BT)', 4, 'BT', 5);
INSERT INTO course (name, credits, branch, semester) VALUES ('Immunology - Sem 5 (BT)', 4, 'BT', 5);
INSERT INTO course (name, credits, branch, semester) VALUES ('Environmental Biotechnology - Sem 5 (BT)', 4, 'BT', 5);
INSERT INTO course (name, credits, branch, semester) VALUES ('Genetics - Sem 5 (BT)', 5, 'BT', 5);
INSERT INTO course (name, credits, branch, semester) VALUES ('Animal Biotechnology - Sem 5 (BT)', 5, 'BT', 5);
INSERT INTO course (name, credits, branch, semester) VALUES ('Genetics - Sem 6 (BT)', 5, 'BT', 6);
INSERT INTO course (name, credits, branch, semester) VALUES ('Immunology - Sem 6 (BT)', 4, 'BT', 6);
INSERT INTO course (name, credits, branch, semester) VALUES ('Plant Biotechnology - Sem 6 (BT)', 5, 'BT', 6);
INSERT INTO course (name, credits, branch, semester) VALUES ('Cell Biology - Sem 6 (BT)', 5, 'BT', 6);
INSERT INTO course (name, credits, branch, semester) VALUES ('Genetic Engineering - Sem 6 (BT)', 4, 'BT', 6);
INSERT INTO course (name, credits, branch, semester) VALUES ('Immunology - Sem 7 (BT)', 5, 'BT', 7);
INSERT INTO course (name, credits, branch, semester) VALUES ('Microbiology - Sem 7 (BT)', 4, 'BT', 7);
INSERT INTO course (name, credits, branch, semester) VALUES ('Biochemistry - Sem 7 (BT)', 4, 'BT', 7);
INSERT INTO course (name, credits, branch, semester) VALUES ('Animal Biotechnology - Sem 7 (BT)', 5, 'BT', 7);
INSERT INTO course (name, credits, branch, semester) VALUES ('Bioinformatics - Sem 7 (BT)', 4, 'BT', 7);
INSERT INTO course (name, credits, branch, semester) VALUES ('Bioinformatics - Sem 8 (BT)', 4, 'BT', 8);
INSERT INTO course (name, credits, branch, semester) VALUES ('Plant Biotechnology - Sem 8 (BT)', 5, 'BT', 8);
INSERT INTO course (name, credits, branch, semester) VALUES ('Microbiology - Sem 8 (BT)', 5, 'BT', 8);
INSERT INTO course (name, credits, branch, semester) VALUES ('Genetics - Sem 8 (BT)', 4, 'BT', 8);
INSERT INTO course (name, credits, branch, semester) VALUES ('Cell Biology - Sem 8 (BT)', 4, 'BT', 8);